name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  speech_to_text: ^7.4.0
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.5.0
  shared_preferences: ^2.5.5
  google_fonts: ^8.1.0
  google_sign_in: ^7.2.0

  # Location & Maps
  geolocator: ^14.0.3
  geocoding: ^4.0.0

  # Image picker & Cloudinary upload
  image_picker: ^1.1.2
  http: ^1.2.1
  csc_picker:
    git:
      url: https://github.com/iamageo/csc_picker.git
      ref: master
  mobile_scanner: ^7.2.0
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icons.png"

flutter:
  uses-material-design: true
  assets:
    - assets/public/
