import 'package:flutter/material.dart';
import 'splash_4.dart';
import 'get_start.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          SplashScreen3(),
        ]),
      ),
    );
  }
}

class SplashScreen3 extends StatelessWidget {
  const SplashScreen3({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(20.0),
          child: Column(
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  const Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: '2',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 18,
                            fontFamily: 'Montserrat',
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                        TextSpan(
                          text: '/3',
                          style: TextStyle(
                            color: Color(0xFFA0A0A1),
                            fontSize: 18,
                            fontFamily: 'Montserrat',
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ],
                    ),
                  ),
                  GestureDetector(
                    onTap: () {
                      Navigator.pushReplacement(
                        context,
                        PageRouteBuilder(
                          pageBuilder: (context, animation, secondaryAnimation) => const GetStarted(),
                          transitionsBuilder: (context, animation, secondaryAnimation, child) {
                            return SlideTransition(
                              position: animation.drive(Tween(begin: const Offset(0.05, 0.0), end: Offset.zero).chain(CurveTween(curve: Curves.easeInOut))),
                              child: FadeTransition(opacity: animation, child: child),
                            );
                          },
                          transitionDuration: const Duration(milliseconds: 500),
                        ),
                      );
                    },
                    child: const Text(
                      'Skip',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 18,
                        fontFamily: 'Montserrat',
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                ],
              ),
              const Spacer(flex: 2),
              Image.asset(
                'assets/public/splash_3.png',
                width: 300,
                height: 300,
                fit: BoxFit.contain,
              ),
              const Spacer(flex: 1),
              const Text(
                'Transaksi COD Aman',
                textAlign: TextAlign.center,
                style: TextStyle(
                  color: Colors.black,
                  fontSize: 24,
                  fontFamily: 'Montserrat',
                  fontWeight: FontWeight.w800,
                ),
              ),
              const SizedBox(height: 20),
              const Text(
                'Gunakan titik temu \'Safe Zone\' yang aman dan terverifikasi untuk melakukan pertemuan COD tanpa rasa khawatir.',
                textAlign: TextAlign.center,
                style: TextStyle(
                  color: Color(0xFFA8A8A9),
                  fontSize: 14,
                  fontFamily: 'Montserrat',
                  fontWeight: FontWeight.w600,
                  height: 1.71,
                ),
              ),
              const Spacer(flex: 2),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  GestureDetector(
                    onTap: () {
                      Navigator.pop(context);
                    },
                    child: const SizedBox(
                      width: 44,
                      child: Text(
                        'Prev',
                        textAlign: TextAlign.left,
                        style: TextStyle(
                          color: Color(0xFFC4C4C4),
                          fontSize: 18,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                  ),
                  Row(
                    children: [
                      _buildInactiveIndicator(),
                      const SizedBox(width: 10),
                      _buildActiveIndicator(),
                      const SizedBox(width: 10),
                      _buildInactiveIndicator(),
                    ],
                  ),
                  GestureDetector(
                    onTap: () {
                      Navigator.push(
                        context,
                        PageRouteBuilder(
                          pageBuilder: (context, animation, secondaryAnimation) => const SplashScreen4(),
                          transitionsBuilder: (context, animation, secondaryAnimation, child) {
                            return SlideTransition(
                              position: animation.drive(Tween(begin: const Offset(0.05, 0.0), end: Offset.zero).chain(CurveTween(curve: Curves.easeInOut))),
                              child: FadeTransition(opacity: animation, child: child),
                            );
                          },
                          transitionDuration: const Duration(milliseconds: 500),
                        ),
                      );
                    },
                    child: const SizedBox(
                      width: 44,
                      child: Text(
                        'Next',
                        textAlign: TextAlign.right,
                        style: TextStyle(
                          color: Color(0xFFF73658),
                          fontSize: 18,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildActiveIndicator() {
    return Container(
      width: 40,
      height: 8,
      decoration: ShapeDecoration(
        color: const Color(0xFF17223B),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(100),
        ),
      ),
    );
  }

  Widget _buildInactiveIndicator() {
    return Container(
      width: 10,
      height: 10,
      decoration: ShapeDecoration(
        color: const Color(0x3317223B),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(100),
        ),
      ),
    );
  }
}