import 'package:flutter/material.dart';
import 'splash_2.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          SplashScreen1(),
        ]),
      ),
    );
  }
}


class SplashScreen1 extends StatefulWidget {
  const SplashScreen1({super.key});

  @override
  State<SplashScreen1> createState() => _SplashScreen1State();
}

class _SplashScreen1State extends State<SplashScreen1> {
  @override
  void initState() {
    super.initState();
    Future.delayed(const Duration(seconds: 3), () {
      if (mounted) {
        Navigator.pushReplacement(
          context,
          MaterialPageRoute(
            builder: (context) => const SplashScreen2(),
          ),
        );
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: SafeArea(
        child: Column(
          children: [
            const Spacer(flex: 3),
            const Center(
              child: Text(
                'SmartDrop',
                textAlign: TextAlign.center,
                style: TextStyle(
                  color: Color(0xFF3B26B7),
                  fontSize: 40,
                  fontFamily: 'Libre Caslon Text',
                  fontWeight: FontWeight.w700,
                ),
              ),
            ),
            const Spacer(flex: 2),
            SizedBox(
              width: 42,
              height: 18,
              child: Stack(
                children: [
                  Positioned(left: 0, top: 12, child: _buildDot()),
                  Positioned(left: 12, top: 8, child: _buildDot()),
                  Positioned(left: 24, top: 0, child: _buildDot()),
                  Positioned(left: 36, top: 9, child: _buildDot()),
                ],
              ),
            ),
            const Spacer(flex: 1),
            Container(
              width: 134,
              height: 5,
              margin: const EdgeInsets.only(bottom: 10),
              decoration: ShapeDecoration(
                color: const Color(0xFFA8A8A9),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(30),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildDot() {
    return Container(
      width: 6,
      height: 6,
      decoration: const ShapeDecoration(
        color: Color(0xFFC4C4C4),
        shape: OvalBorder(),
      ),
    );
  }
}