// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUQwnw3NJIYoLywxhdYzOK4Xlq0wDP58k',
    appId: '1:171891372687:web:b6b383e137202453a9f6fa',
    messagingSenderId: '171891372687',
    projectId: 'smartdrop-55228',
    authDomain: 'smartdrop-55228.firebaseapp.com',
    storageBucket: 'smartdrop-55228.firebasestorage.app',
    measurementId: 'G-F6XBNRCXP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm5iu-zPvpMuUD8-8BXRg4kqwgV_0OVHI',
    appId: '1:171891372687:android:dfe2d31905e8b954a9f6fa',
    messagingSenderId: '171891372687',
    projectId: 'smartdrop-55228',
    storageBucket: 'smartdrop-55228.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFbzhghfCb0aefTR8lfsvqC_AnfDOXnUM',
    appId: '1:171891372687:ios:07c757d51c78d797a9f6fa',
    messagingSenderId: '171891372687',
    projectId: 'smartdrop-55228',
    storageBucket: 'smartdrop-55228.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFbzhghfCb0aefTR8lfsvqC_AnfDOXnUM',
    appId: '1:171891372687:ios:07c757d51c78d797a9f6fa',
    messagingSenderId: '171891372687',
    projectId: 'smartdrop-55228',
    storageBucket: 'smartdrop-55228.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUQwnw3NJIYoLywxhdYzOK4Xlq0wDP58k',
    appId: '1:171891372687:web:a5f78986fcc0e9c1a9f6fa',
    messagingSenderId: '171891372687',
    projectId: 'smartdrop-55228',
    authDomain: 'smartdrop-55228.firebaseapp.com',
    storageBucket: 'smartdrop-55228.firebasestorage.app',
    measurementId: 'G-K18WXJM30E',
  );

}